// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0AXD2roxOm30_NOs4gd8kpBbvkeoyJu0',
    appId: '1:802249753504:web:9e1ce92e5348bdd32a5ac5',
    messagingSenderId: '802249753504',
    projectId: 'erazor-73960',
    authDomain: 'erazor-73960.firebaseapp.com',
    storageBucket: 'erazor-73960.appspot.com',
    measurementId: 'G-DFSYTKE4X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc2lmZUMjeHsiI8pDUzrNlw2ziQ5lK76s',
    appId: '1:802249753504:android:2ba37adec621c0802a5ac5',
    messagingSenderId: '802249753504',
    projectId: 'erazor-73960',
    storageBucket: 'erazor-73960.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsWbS2v0MPp9W6XLoR9F7j5x6kKAimwVc',
    appId: '1:802249753504:ios:2a97501e465c816c2a5ac5',
    messagingSenderId: '802249753504',
    projectId: 'erazor-73960',
    storageBucket: 'erazor-73960.appspot.com',
    androidClientId: '802249753504-65u9phpenk7jcns61d3povd0o9da2ruk.apps.googleusercontent.com',
    iosClientId: '802249753504-149s7almp69tpu9pff1v02vq359bc9oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.erazorPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsWbS2v0MPp9W6XLoR9F7j5x6kKAimwVc',
    appId: '1:802249753504:ios:1e4679cc6d6427802a5ac5',
    messagingSenderId: '802249753504',
    projectId: 'erazor-73960',
    storageBucket: 'erazor-73960.appspot.com',
    androidClientId: '802249753504-65u9phpenk7jcns61d3povd0o9da2ruk.apps.googleusercontent.com',
    iosClientId: '802249753504-ohc6sgebgfjb32gb024fapnomarv6pa8.apps.googleusercontent.com',
    iosBundleId: 'com.example.erazorPartner.RunnerTests',
  );
}
